version: '3.7'
services:
  db: 
    image: postgres:15
    container_name: support_db
    env_file:
      - .env-non-dev
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: support_redis

  app:
    build:
      context: .
    container_name: support_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/backend/docker/app.sh"]
    ports:
      - 8000:8000

  celery:
    build:
      context: .
    container_name: support_celery
    command: ["/backend/docker/celery.sh"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgresdata: