"""edit index

Revision ID: 0bac68089951
Revises: 8c44c6046482
Create Date: 2025-01-08 02:53:26.790810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bac68089951'
down_revision: Union[str, None] = '8c44c6046482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('created_at_index', 'event', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('created_at_index', table_name='event')
    # ### end Alembic commands ###
