"""empty message

Revision ID: 27a55f1b341a
Revises: d6311dcfc925
Create Date: 2024-10-03 12:24:35.717540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a55f1b341a'
down_revision: Union[str, None] = 'd6311dcfc925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('organization', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'longitude')
    op.drop_column('organization', 'latitude')
    # ### end Alembic commands ###
