"""edit index

Revision ID: 32dd17885d70
Revises: d204123e477f
Create Date: 2025-01-06 01:38:40.542270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dd17885d70'
down_revision: Union[str, None] = 'd204123e477f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('FIO_index', table_name='organization')
    op.drop_index('name_organization_index', table_name='organization')
    op.create_index('name_organization_and_FIO_index', 'organization', ['name_organization', 'FIO'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_organization_and_FIO_index', table_name='organization')
    op.create_index('name_organization_index', 'organization', ['name_organization'], unique=False)
    op.create_index('FIO_index', 'organization', ['FIO'], unique=False)
    # ### end Alembic commands ###
