"""edit index

Revision ID: 538cfdf4f650
Revises: a9a23f074388
Create Date: 2025-01-06 01:29:29.308820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538cfdf4f650'
down_revision: Union[str, None] = 'a9a23f074388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('FIO_index', 'organization', ['FIO'], unique=False)
    op.create_index('name_organization_index', 'organization', ['name_organization'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_organization_index', table_name='organization')
    op.drop_index('FIO_index', table_name='organization')
    # ### end Alembic commands ###
