"""edit index

Revision ID: 74b7ee0964c4
Revises: ca6ba95ac064
Create Date: 2025-01-08 01:52:13.792309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b7ee0964c4'
down_revision: Union[str, None] = 'ca6ba95ac064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('short_text_index', table_name='event')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('short_text_index', 'event', ['short_text'], unique=False)
    # ### end Alembic commands ###
