"""edit index

Revision ID: 8c44c6046482
Revises: 74b7ee0964c4
Create Date: 2025-01-08 02:11:53.688789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c44c6046482'
down_revision: Union[str, None] = '74b7ee0964c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_city_index', 'event', ['id_city'], unique=False)
    op.create_index('id_organization_index', 'event', ['id_organization'], unique=False)
    op.create_index('id_type_event_index', 'event', ['id_type_event'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_type_event_index', table_name='event')
    op.drop_index('id_organization_index', table_name='event')
    op.drop_index('id_city_index', table_name='event')
    # ### end Alembic commands ###
