"""add recovery password code

Revision ID: 916ea38dc8e0
Revises: 27a55f1b341a
Create Date: 2024-12-20 20:47:22.307862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916ea38dc8e0'
down_revision: Union[str, None] = '27a55f1b341a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('recovery_password_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'recovery_password_code')
    # ### end Alembic commands ###
