"""edit index

Revision ID: a9a23f074388
Revises: c71d008731c9
Create Date: 2025-01-06 00:24:37.273917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a23f074388'
down_revision: Union[str, None] = 'c71d008731c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email_index', table_name='organization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email_index', 'organization', ['email'], unique=False)
    # ### end Alembic commands ###
