"""edit index

Revision ID: ab0b0e8a7b47
Revises: 0bac68089951
Create Date: 2025-01-08 02:55:30.378168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0b0e8a7b47'
down_revision: Union[str, None] = '0bac68089951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('created_at_index', table_name='event')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('created_at_index', 'event', ['created_at'], unique=False)
    # ### end Alembic commands ###
