"""edit index

Revision ID: c71d008731c9
Revises: 5c0941cc2d72
Create Date: 2025-01-06 00:20:08.955916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71d008731c9'
down_revision: Union[str, None] = '5c0941cc2d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('from_index', 'comment', ['id_from'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('from_index', table_name='comment')
    # ### end Alembic commands ###
