"""edit index

Revision ID: ca6ba95ac064
Revises: f86da6a41364
Create Date: 2025-01-08 01:51:56.255785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6ba95ac064'
down_revision: Union[str, None] = 'f86da6a41364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('theme_event_index', table_name='theme_event')
    op.drop_index('type_event_index', table_name='type_event')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('type_event_index', 'type_event', ['type_event'], unique=False)
    op.create_index('theme_event_index', 'theme_event', ['theme_event'], unique=False)
    # ### end Alembic commands ###
