"""empty message

Revision ID: d6311dcfc925
Revises: bcefe911f37e
Create Date: 2024-10-02 17:19:11.907141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6311dcfc925'
down_revision: Union[str, None] = 'bcefe911f37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'id_city',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'id_city',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
