"""edit index

Revision ID: f86da6a41364
Revises: 32dd17885d70
Create Date: 2025-01-06 01:44:43.270419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86da6a41364'
down_revision: Union[str, None] = '32dd17885d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_organization_and_FIO_index', table_name='organization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_organization_and_FIO_index', 'organization', ['name_organization', 'FIO'], unique=False)
    # ### end Alembic commands ###
