services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - .env

  cache:
    image: redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672