name: CI/CD for Support App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout кода
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Настройка SSH
    # - name: Set up SSH
    #   uses: webfactory/ssh-agent@v0.5.3
    #   with:
    #     ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
    - name: Unlock SSH key
      run: |
        echo "${{ secrets.SSH_KEY_PASSPHRASE }}" | ssh-add -

    # 3. Проверка Docker Compose
    - name: Lint Docker Compose
      run: docker-compose -f docker-compose.yml config

    # 4. Сборка Docker образов
    - name: Build Docker images
      run: |
        docker-compose -f docker-compose.yml build

    # 5. Копирование файлов на сервер
    - name: Deploy files to server
      run: |
        ssh -o StrictHostKeyChecking=no user@176.123.167.12 "mkdir -p ~/app"
        rsync -avz --exclude=".git" ./ user@176.123.167.12:~/app/

    # 6. Запуск Docker Compose на сервере
    - name: Restart application
      run: |
        ssh -o StrictHostKeyChecking=no user@176.123.167.12 << 'EOF'
          cd ~/app
          docker-compose down
          docker-compose up -d --build
        EOF
